"""Project Manager (PM) agent.

Responsible for requirements decomposition, milestone scheduling,
epic/feature definition, and granular task planning based on CTO architecture.
"""

from typing import Any
from pydantic import BaseModel, Field, field_validator

from app.models.agent import AgentInput, AgentOutput
from app.router.llm import call_llm

SYSTEM_PROMPT = """You are the Project Manager (PM). Deconstruct the technical architecture and requirements into a structured development plan.
Return strict JSON with keys:
epics (list of strings),
features (list of strings),
tasks (list of objects with keys: id, title, description, dependencies, priority, acceptance_criteria, assigned_role),
milestones (list of strings),
risks (list of strings).

Rules:
- Tasks must be concrete, actionable engineering items.
- dependencies must be a list of task IDs.
- priority must be high, medium, or low.
- acceptance_criteria must be a list of strings.
- assigned_role should be one of: team_lead, developer, uiux, qa, ai_engineer.
- no markdown fences.
"""


class PMTask(BaseModel):
    """Granular task definition generated by the PM."""
    id: str
    title: str
    description: str = ""
    dependencies: list[str] = Field(default_factory=list)
    priority: str = "medium"
    acceptance_criteria: list[str] = Field(default_factory=list)
    assigned_role: str = "developer"

    @field_validator("acceptance_criteria", mode="before")
    @classmethod
    def _coerce_criteria(cls, v: Any) -> list[str]:
        if isinstance(v, str):
            return [v.strip()] if v.strip() else []
        if isinstance(v, list):
            return [str(x) for x in v]
        return []

    @field_validator("dependencies", mode="before")
    @classmethod
    def _coerce_deps(cls, v: Any) -> list[str]:
        if isinstance(v, str):
            return [v.strip()] if v.strip() else []
        if isinstance(v, list):
            return [str(x) for x in v]
        return []


class PMOutput(BaseModel):
    """Structured artifact schema produced by the PM agent."""
    epics: list[str] = Field(default_factory=list)
    features: list[str] = Field(default_factory=list)
    tasks: list[PMTask] = Field(default_factory=list)
    milestones: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)


def run_pm(inp: AgentInput) -> AgentOutput:
    """Execute PM task planning on the provided AgentInput and return AgentOutput."""
    cto_context = inp.context.get("cto_artifacts", inp.context)
    prompt = (
        f"Objective: {inp.objective}\n"
        f"Task: {inp.task}\n"
        f"CTO Architecture & Context: {cto_context}\n"
        f"Constraints: {inp.constraints}\n"
        f"Acceptance Criteria: {inp.acceptance_criteria}"
    )

    result = call_llm(
        prompt=prompt,
        task_type="doc",
        complexity="any",
        system=SYSTEM_PROMPT,
        json_mode=True,
        project_id=inp.project_id or "default",
        agent="pm",
    )

    parsed = PMOutput.model_validate_json(result["text"])
    summary = f"PM plan synthesized with {len(parsed.tasks)} tasks across {len(parsed.epics)} epics."

    return AgentOutput(
        status="ok",
        summary=summary,
        actions=[
            f"Defined {len(parsed.epics)} epics",
            f"Generated {len(parsed.tasks)} tasks",
            f"Scheduled {len(parsed.milestones)} milestones",
        ],
        artifacts=parsed.model_dump(),
        risks=parsed.risks,
        next_action="team_lead",
        meta=result,
    )
